FROM ubuntu

RUN sudo apt-get update
RUN sudo apt-get install -y vim git
RUN sudo apt-get install -y python3 python3-setuptools python3-pip
RUN pip3 install jsonschema

# Dependency for python-bitcoinlib
RUN sudo apt-get install -y libssl-dev

ADD . /opt/code/pln/

EXPOSE 8090

WORKDIR /opt/code/pln
CMD ./init.sh && python3 src/main.py

